name: Actions workflow

#on: [push]
on:
#  push:
#    branches:
#      - main
#      - 'feature/*'            #matches anything with feature/featA feature/featB
#      - 'feature/**'           #matches anything like: feature/featA/a    feature/featB/b
#      - '!feature/featC'
#    tags:
#      - v1.*
##    path:
##      - '**.js'    #    # this path will run the workflow only any changes in js file not other file
##    path-ignore:
##      - 'docs/**'



  #  repository_dispatch:
#    types: [build]
#    steps:
#      - name: payload
#        run: echo "${{github.event.client_payload.env}}"

#  schedule:
#    - corn: "0 * * * 6" # "minute hour dayOfMonth month dayOfWeek"  *  means any value   0/15 means every 15 minutes
#  push:
  pull_request:
    types: [closed, assigned, opened, reopened]


jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1

      - name: List Files after checkout
        run: |
          pwd
          ls -a
      - name: simple js actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"


