name: shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline-script
        run: |   # | this is pipe and to run multiline commands
          node -v
          npm -v
      - name: python platform
        run: |
          import platform
          print(platform.processor())
        shell: python # telling github to run above commands not in bash shell but in python shell
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory-powershell
        run: Get-location
      - name: Directory Bash
        run: pwd
        shell: bash # telling github to run above commands on bash not in powershell
